language: python
aaa:
  - 1.0
  - 2.0
python:
  - "2.6"
  - "3.2"

script:
  - cat .travis.yml
  - python --version

before_install:
  - echo before_install
install:
  - echo install
before_script:
  - echo before_script
after_success:
  - echo after_success
after_failure:
  - echo after_failure
after_script:
  - echo after_script
