language: bash
before_script:
  - git config --global user.email "rcmdnk@gmail.com"
  - git config --global user.name "rcmdnk"
  - git config --global push.default simple
script:
  - touch testfile
  - git commit -m "test commit"
  - git push
  - git push -f https://c27a5bd6c09cb9b51790f08adffe9c963542088c@github.com/rcmdnk/travis-test master
