language: java
install:
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew update || true'
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew install ant || true'
script:
  - cat .travis.yml
  - echo test
os:
  - linux
  - osx
